# Generated by Django 3.0.2 on 2020-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tag',
            field=models.CharField(choices=[('Feautured', 'Featured'), ('People', 'People'), ('Travel', 'Travel'), ('Nature', 'Nature'), ('Animal', 'Animal')], max_length=10),
        ),
    ]
