# Generated by Django 3.0.2 on 2020-03-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200305_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='author',
            field=models.CharField(default='Arthur Rose', max_length=15),
        ),
    ]
